## Handling Imbalanced Dataset

1. Up Sampling: If we have a lot of missing values in the data, we can use up sampling to fill the missing values. We can use the mean, median, or mode of the data to fill the missing values. 
2. Down Sampling: If we have a lot of missing values in the data, we can use down sampling to fill the missing values. We can use the mean, median, or mode of the data to fill the missing values.

In [1]:
 import pandas as pd
 import numpy as np

In [2]:
# Set the random seed for reproducibility
np.random.seed(42)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [4]:
# Create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0), 
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1), 
    'target': [1] * n_class_1
})

In [5]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.tail()

     feature_1  feature_2  target
995   1.629989   3.070150       1
996   1.741204   1.973479       1
997   3.598647   1.118125       1
998   2.560919   1.836933       1
999   1.704520   1.255097       1

In [7]:
df.target.unique()

array([0, 1], dtype=int64)

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Up-Sampling

In [9]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [10]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace=True, # sample with replacement
                                 n_samples=len(df_majority), # match number in majority class
                                 random_state=42) # reproducible results

In [11]:
df_minority_upsampled.shape

(900, 3)

In [12]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   3.775311   3.261922       1
992   1.563614   3.188913       1
914   1.731469   0.198942       1
971   1.785079  -0.940389       1
960   1.865691   1.945106       1

In [13]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [14]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down-Sampling

In [15]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [16]:
# Downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [17]:
from sklearn.utils import resample

df_majority_downsampled=resample(df_majority,replace=False,
         n_samples=len(df_minority), # length of minority class
         random_state=42
        )

In [18]:
df_majority_downsampled.shape

(100, 3)

In [19]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [20]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

- Note: 
1. Down Sampling is not recommended when you have a small dataset as it can lead to loss of information. It is generally used when you have a large dataset and want to reduce the training time of your model.
2. Down sampling is bad compared to up sampling because it can lead to loss of information. Up sampling is generally preferred when you have a small dataset and want to increase the number of samples in the minority class.